# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        files: ^server/
      - id: trailing-whitespace
        files: ^server/
      - id: check-toml
        files: ^server/
      - id: end-of-file-fixer
        files: ^server/

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.0
    hooks:
      - id: add-trailing-comma
        files: ^server/

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.9.0
    hooks:
      - id: pretty-format-yaml
        args:
          - --autofix
          - --preserve-quotes
          - --indent=2
        files: ^server/

  - repo: local
    hooks:
      - id: black
        name: Format with Black
        entry: poetry run black
        language: system
        types: [python]
        files: ^server/

      - id: autoflake
        name: autoflake
        entry: poetry run autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]
        files: ^server/

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        files: ^server/

      - id: flake8
        name: Check with Flake8
        entry: poetry run flake8
        language: system
        pass_filenames: false
        types: [python]
        args: [--count, ., --exclude, packages]
        files: ^server/

      - id: mypy
        name: Validate types with MyPy
        entry: poetry run mypy
        language: system
        types: [python]
        pass_filenames: false
        args:
          - "server"
        files: ^server/
